name: build-and-test

on:
  push:
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - "docs/**"
      - "images/**"
      - ".github/ISSUE_TEMPLATE/**"

  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - "docs/**"
      - "images/**"
      - ".github/ISSUE_TEMPLATE/**"

jobs:
  lint:
    name: (Lint ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install nox
        run: pip install nox

      - name: Code format
        run: nox -s linter

      - name: Spell check
        run: nox -s codespell  

  tests:
    name: (Test ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest, windows-latest, ubuntu-latest]
        python-version: ["3.9", "3.13"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install {{ cookiecutter.package_name }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade nox
          pip install .[tests]
                
      - name: Pytest
        run: nox -s tests -- no-reports